name: Promote reference init-script

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true


permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Generate reference script with version
        run: ./gradlew promote -Pversion=${{ inputs.version }}
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.DV_ACCESS_KEY }}

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[bot] Promote reference script'
          tagging_message: '${{ inputs.version }}'
  
  gradle-actions-promotion:
    needs: update-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: 'gradle/actions'
          path: actions


      - run: |
          ls -la .
          ls -la actions
          cp reference/develocity-auto-injection.init.gradle actions/renamed-script.init.gradle
          ls -la actions

      # - name: Copy reference script
      #   run: cp reference/develocity-auto-inject.init.gradle actions/sources/src/resources/init-scripts/gradle-actions.init-develocity.init.gradle

      - name: Git diff
        run: git diff
        working-directory: actions
