name: Promote reference init-script

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true


permissions:
  contents: write
  pull-requests: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Generate reference script with version
        run: ./gradlew promote -Pversion=${{ inputs.version }}
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.DV_ACCESS_KEY }}

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[bot] Promote reference script'
          tagging_message: '${{ inputs.version }}'
  
  gradle-actions-promotion:
    needs: update-version
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: 'gradle/actions'
          path: actions

      - name: Copy reference script
        run: cp reference/develocity-auto-injection.init.gradle actions/sources/src/resources/init-scripts/gradle-actions.init-develocity.init.gradle

      # If there are no changes, this action will not create a pull request
      - name: Create or update pull request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: bot/init-script-update
          commit-message: Update develocity-auto-inject init script
          title: Update develocity-auto-inject init script
          path: actions
